//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationKeys {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationKeys() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.ConfigurationKeys", typeof(ConfigurationKeys).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGCOLOUR_EMPTY_TD.
        /// </summary>
        internal static string BGCOLOUR_EMPTY_TD {
            get {
                return ResourceManager.GetString("BGCOLOUR_EMPTY_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BGCOLOUR_NON_EMPTY_TD.
        /// </summary>
        internal static string BGCOLOUR_NON_EMPTY_TD {
            get {
                return ResourceManager.GetString("BGCOLOUR_NON_EMPTY_TD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERSECTING_POINTS_PER_LETTER.
        /// </summary>
        internal static string INTERSECTING_POINTS_PER_LETTER {
            get {
                return ResourceManager.GetString("INTERSECTING_POINTS_PER_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_CROZZLE_SCORE.
        /// </summary>
        internal static string INVALID_CROZZLE_SCORE {
            get {
                return ResourceManager.GetString("INVALID_CROZZLE_SCORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGFILE_NAME.
        /// </summary>
        internal static string LOGFILE_NAME {
            get {
                return ResourceManager.GetString("LOGFILE_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_HORIZONTAL_WORDS.
        /// </summary>
        internal static string MAXIMUM_HORIZONTAL_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_HORIZONTAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS.
        /// </summary>
        internal static string MAXIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_INTERSECTIONS_IN_VERTICAL_WORDS.
        /// </summary>
        internal static string MAXIMUM_INTERSECTIONS_IN_VERTICAL_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_INTERSECTIONS_IN_VERTICAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_NUMBER_OF_COLUMNS.
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_COLUMNS {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_NUMBER_OF_GROUPS.
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_GROUPS {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_NUMBER_OF_ROWS.
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_ROWS {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_NUMBER_OF_THE_SAME_WORD.
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_THE_SAME_WORD {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_THE_SAME_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_NUMBER_OF_UNIQUE_WORDS.
        /// </summary>
        internal static string MAXIMUM_NUMBER_OF_UNIQUE_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_NUMBER_OF_UNIQUE_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAXIMUM_VERTICAL_WORDS.
        /// </summary>
        internal static string MAXIMUM_VERTICAL_WORDS {
            get {
                return ResourceManager.GetString("MAXIMUM_VERTICAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_HORIZONTAL_WORDS.
        /// </summary>
        internal static string MINIMUM_HORIZONTAL_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_HORIZONTAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS.
        /// </summary>
        internal static string MINIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_INTERSECTIONS_IN_HORIZONTAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_INTERSECTIONS_IN_VERTICAL_WORDS.
        /// </summary>
        internal static string MINIMUM_INTERSECTIONS_IN_VERTICAL_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_INTERSECTIONS_IN_VERTICAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_NUMBER_OF_COLUMNS.
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_COLUMNS {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_COLUMNS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_NUMBER_OF_GROUPS.
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_GROUPS {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_GROUPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_NUMBER_OF_ROWS.
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_ROWS {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_ROWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_NUMBER_OF_THE_SAME_WORD.
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_THE_SAME_WORD {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_THE_SAME_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_NUMBER_OF_UNIQUE_WORDS.
        /// </summary>
        internal static string MINIMUM_NUMBER_OF_UNIQUE_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_NUMBER_OF_UNIQUE_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MINIMUM_VERTICAL_WORDS.
        /// </summary>
        internal static string MINIMUM_VERTICAL_WORDS {
            get {
                return ResourceManager.GetString("MINIMUM_VERTICAL_WORDS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NON_INTERSECTING_POINTS_PER_LETTER.
        /// </summary>
        internal static string NON_INTERSECTING_POINTS_PER_LETTER {
            get {
                return ResourceManager.GetString("NON_INTERSECTING_POINTS_PER_LETTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POINTS_PER_WORD.
        /// </summary>
        internal static string POINTS_PER_WORD {
            get {
                return ResourceManager.GetString("POINTS_PER_WORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to STYLE.
        /// </summary>
        internal static string STYLE {
            get {
                return ResourceManager.GetString("STYLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPPERCASE.
        /// </summary>
        internal static string UPPERCASE {
            get {
                return ResourceManager.GetString("UPPERCASE", resourceCulture);
            }
        }
    }
}
