//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigurationErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigurationErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.ConfigurationErrors", typeof(ConfigurationErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1004: key-value pair ({0}), colour is {1}.
        /// </summary>
        internal static string ColourError {
            get {
                return ResourceManager.GetString("ColourError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1006: key-value pair ({0}), key already used.
        /// </summary>
        internal static string DuplicateKeyError {
            get {
                return ResourceManager.GetString("DuplicateKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1005: invalid characters in filename ({0}).
        /// </summary>
        internal static string FilenameError {
            get {
                return ResourceManager.GetString("FilenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1002: key-value pair ({0}), integer is {1}.
        /// </summary>
        internal static string IntegerError {
            get {
                return ResourceManager.GetString("IntegerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1010: the value of {0} is {1} which is greater than the counterpart maximum value of {2}.
        /// </summary>
        internal static string MinGreaterThanMaxError {
            get {
                return ResourceManager.GetString("MinGreaterThanMaxError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1008: key ({0}) is missing from the intersection points.
        /// </summary>
        internal static string MissingIntersectionKeyError {
            get {
                return ResourceManager.GetString("MissingIntersectionKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1007: key ({0}) is missing from the configuration file.
        /// </summary>
        internal static string MissingKeyError {
            get {
                return ResourceManager.GetString("MissingKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1009: key ({0}) is missing from the non-intersection points.
        /// </summary>
        internal static string MissingNonIntersectionKeyError {
            get {
                return ResourceManager.GetString("MissingNonIntersectionKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1003: key-value pair ({0}), style is {1}.
        /// </summary>
        internal static string StyleError {
            get {
                return ResourceManager.GetString("StyleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 1001: key-value pair ({0}), value is {1}.
        /// </summary>
        internal static string ValueError {
            get {
                return ResourceManager.GetString("ValueError", resourceCulture);
            }
        }
    }
}
