//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrozzleErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrozzleErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.CrozzleErrors", typeof(CrozzleErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11005: the number of groups of connected words is {0}, but this is not within [{1}, {2}].
        /// </summary>
        internal static string ConnectivityError {
            get {
                return ResourceManager.GetString("ConnectivityError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11003: the number of times {0} occurs is {1}, but this is not within [{2}, {3}].
        /// </summary>
        internal static string DuplicateWordCountError {
            get {
                return ResourceManager.GetString("DuplicateWordCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11002: the number of horizontal words intersecting {0} is {1}, but this is not within [{2}, {3}].
        /// </summary>
        internal static string HorizontalIntersectionsError {
            get {
                return ResourceManager.GetString("HorizontalIntersectionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11007: the number of horizontal words is {0}, but this is not within [{1}, {2}].
        /// </summary>
        internal static string HorizontalWordCountError {
            get {
                return ResourceManager.GetString("HorizontalWordCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11009: the horizontal word ({0}) doesn&apos;t fit into grid.
        /// </summary>
        internal static string HorizontalWordSizeError {
            get {
                return ResourceManager.GetString("HorizontalWordSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11011: {0} at ({1}, {2}) is not in the word list.
        /// </summary>
        internal static string MissingFromWordlistError {
            get {
                return ResourceManager.GetString("MissingFromWordlistError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11001: the number of vertical words intersecting {0} is {1}, but this is not within [{2}, {3}].
        /// </summary>
        internal static string VerticalIntersectionsError {
            get {
                return ResourceManager.GetString("VerticalIntersectionsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11008: the number of vertical words is {0} but this is not within [{1}, {2}].
        /// </summary>
        internal static string VerticalWordCountError {
            get {
                return ResourceManager.GetString("VerticalWordCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11010: the vertical word ({0}) doesn&apos;t fit into grid.
        /// </summary>
        internal static string VerticalWordSizeError {
            get {
                return ResourceManager.GetString("VerticalWordSizeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 11006: the number of words is {0}, but this is not within ({1}, {2}).
        /// </summary>
        internal static string WordCountError {
            get {
                return ResourceManager.GetString("WordCountError", resourceCulture);
            }
        }
    }
}
