//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CrozzleFileErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CrozzleFileErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.CrozzleFileErrors", typeof(CrozzleFileErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 4008: the number of columns ({0}) is not within [{1}, {2}].
        /// </summary>
        internal static string ColumnCountError {
            get {
                return ResourceManager.GetString("ColumnCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 4006: the value in the key-value ({0}) is {1}.
        /// </summary>
        internal static string ColumnError {
            get {
                return ResourceManager.GetString("ColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 4002: configuration filename ({0}) doesn&apos;t match filename in the configuration object ({1}).
        /// </summary>
        internal static string ConfigurationFilenameError {
            get {
                return ResourceManager.GetString("ConfigurationFilenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 4001: configuration filename is missing from the crozzle file.
        /// </summary>
        internal static string ConfigurationFilenameMissing {
            get {
                return ResourceManager.GetString("ConfigurationFilenameMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 4007: the number of rows ({0}) is not within [{1}, {2}].
        /// </summary>
        internal static string RowCountError {
            get {
                return ResourceManager.GetString("RowCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 4005: the value in the key-value ({0}) is {1}.
        /// </summary>
        internal static string RowError {
            get {
                return ResourceManager.GetString("RowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 4004: wordlist filename ({0}) doesn&apos;t match filename in the wordlist object ({1}).
        /// </summary>
        internal static string WordlistFilenameError {
            get {
                return ResourceManager.GetString("WordlistFilenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 4003: wordlist filename is missing from the crozzle file.
        /// </summary>
        internal static string WordlistFilenameMissing {
            get {
                return ResourceManager.GetString("WordlistFilenameMissing", resourceCulture);
            }
        }
    }
}
