//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class KeyValueErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal KeyValueErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.KeyValueErrors", typeof(KeyValueErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 6001: {0} fields in key-value pair ({1}), instead of {2}.
        /// </summary>
        internal static string FieldCountError {
            get {
                return ResourceManager.GetString("FieldCountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 6002: invalid key in key-value pair ({0}).
        /// </summary>
        internal static string InvalidKeyError {
            get {
                return ResourceManager.GetString("InvalidKeyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 6005: missing = symbol in key-value pair ({0}).
        /// </summary>
        internal static string MissingEqualsError {
            get {
                return ResourceManager.GetString("MissingEqualsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 6004: missing value in key-value pair ({0}).
        /// </summary>
        internal static string MissingValueError {
            get {
                return ResourceManager.GetString("MissingValueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to code 6003: null value in key-value pair ({0}).
        /// </summary>
        internal static string NullValueError {
            get {
                return ResourceManager.GetString("NullValueError", resourceCulture);
            }
        }
    }
}
