//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrozzleApplication {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidatorErrors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidatorErrors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CrozzleApplication.ValidatorErrors", typeof(ValidatorErrors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not a Boolean.
        /// </summary>
        internal static string BooleanError {
            get {
                return ResourceManager.GetString("BooleanError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not delimited by any character in ({0}).
        /// </summary>
        internal static string DelimiterError {
            get {
                return ResourceManager.GetString("DelimiterError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to invalid characters found in filename.
        /// </summary>
        internal static string FilenameError {
            get {
                return ResourceManager.GetString("FilenameError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not a Hex colour code.
        /// </summary>
        internal static string HexColourCodeError {
            get {
                return ResourceManager.GetString("HexColourCodeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not an integer.
        /// </summary>
        internal static string IntegerError {
            get {
                return ResourceManager.GetString("IntegerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not matching the pattern {0}.
        /// </summary>
        internal static string PatternError {
            get {
                return ResourceManager.GetString("PatternError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not in the range {0} to {1}, inclusive.
        /// </summary>
        internal static string RangeError {
            get {
                return ResourceManager.GetString("RangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not a HTML style.
        /// </summary>
        internal static string StyleError {
            get {
                return ResourceManager.GetString("StyleError", resourceCulture);
            }
        }
    }
}
